server:
  port: 9527

spring:
  application:
    name: cloud-provider-gateway-payment
  cloud:
    gateway:
      discovery:
        locator:
          #开启注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        - id: payment_routh
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
            #- Cookie=userName,zzyy




eureka:
  instance:
    instance-id: gateway9527
    prefer-ip-address: true #访问路径可以显示IP地址
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
    #  defaultZone: http://localhost:7001/eureka  #单机版







